image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew

  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)


build_script:

  - ./gradlew test --info -Selenide.headless=true